use_package("devtools")
use_package("usethis")
use_package("tidyr")
use_package("dplyr")
use_package("ggplot2")
use_package("vroom")
use_package("here")
use_package("tidytext")
use_package("topicmodels")
use_package("readxl")
use_package("janitor")
use_package("shiny")
use_package("rsample")
use_package("recipes")
use_package("parsnip")
use_package("yardstick")

use_tidy_description()
